CREATE VIEW INFO_COTIZACION AS 
	SELECT
        cot.ID_COTIZACION AS COTIZACION,
	    p.ID_PRODUCTO AS ID,
	    p.NOMBRE AS NOMBRE,
	    cot.PRECIO_VENTA AS PRECIO,
	    cot.CANTIDAD AS CANTIDAD
	FROM detalle_cotizacion as cot
	    INNER JOIN productos AS p on p.ID_PRODUCTO = cot.ID_PRODUCTO
	WHERE cot.ID_COTIZACION = 40
; 